### ISSUE TITLE
where to place version identifier for json objects

### ISSUE THREAD

**Issue by Legion2** [VirtualProgrammingLab/documentation#1]
Option 1:
Place version in top level json object:
```
{
  "version": "3.0.0",
  "identifier": "11483f23-95bf-424a-98a5-ee5868c85c3e",
  "metadata": { ... },
...
}
```

Option 2:
Use an additional json object as wrapper for the json object.
The wrapper object indicate the type and version of the wrappen object:
```
{
  "version": "3.0.0",
  "ComputationTemplate": {
    "identifier": "11483f23-95bf-424a-98a5-ee5868c85c3e",
    "metadata": {...},
    ...
  }
}
```

Option 2 makes it easy to add information that is only required when the json is transferred to other applications or stored. The domain object itself is not modified, but stored and transferred with additional metadata, like an envelope.

**Comment by pascalseeland** [comment]
I would prefer Option 1, since the template is the only object that gets stored and might exist in some databases for a long time or if published on a datarepository might never change. Adding the information only to the wrapper would require to store the template-version in addition to the template itself. 

For dealing with it on the API level, I would suggest using either different paths (in case of the websocket API (like /computation-v3/v4/v5) or headers (in case of rest api). If we want to stick with one path, we could also add to version to both, but I don't think we need this.

**Comment by Legion2** [comment]
The ComputationTask is also stored in systems like ilias when the solution must be evaluated by a server.

**Comment by Legion2** [comment]
It's clear that we have to define different versions of the json format and there will be new versions added later for new features or bug fixes. So the question is on which level do we handle the versions?

The json format defined is for the APIs of the system, the json format can also be used to store the messages but external systems (e.g. ilias) are not required to do so. They can use own formats to store the data and convert them only when sending to the ViPLab API.

How do we handle compatibility with different versions of the messages? Does the API only accept one version and can the ViPLab client handle multiple versions?

If we only want to support one version (+minor changes) I would suggest to do versioning on the API endpoints. So the endpoints have a version prefix or version header, while the json message does not contain any version identifier. Logically the json message has a specific version determined by the endpoint version. This way the whole system has one version and clear semantics and there are no messages with different versions in the same system.

**Comment by pascalseeland** [comment]
I don't like the idea of having an additional wrapper object. I would prefer to version the objects itself. I would also version all objects in a way, that we can identify on the top level object what to expect. The following list contains the object that I think need a version:
- ComputationTemplate: This object exist as standalone JSON
- CreateComputation (we don't have any documentation yet): As it wraps the ComputationTemplate as base64 encode content, making it cumbersome to get the version. 
I would not version the ComputationTask, as it can only exist inside a CreateComputation when being transferred.
- Result: As they might get save on the client side itself, I think it would be a good idea to provide some kind of version tag as well.

I'm unsure about the Computation. We only need it to be transferred between the API and the backends. 
But we could just version then as well. Just for consistency reasons. And we can just version the ComputationTask as well. 

I don't see that any of the frontend (ILIAS/Dataverse) will use there own structure to store the different artifacts. They will store the JSON as blobs. Thus, I think it will be necessary to have a version identifier in the objects.

I think we will need to support different version of the messages on the API. I would vote for versioning the endpoints as well as the objects. I think we should make it possible to  generate the API endpoint or required headers from the version contained in the object. For transmitting the objects using AMQP, we should use tags so we can apply filters, enabling the different backends to only support one version of the API.

**Comment by Legion2** [comment]
Ok I agree that when we apply versioning to the objects, then all objects must have a version for consistency.

The CreateComputation is not a messages like the ComputationTemplate, it's only a mean to express an action in the websocket api (like an SOAP command message). CreateComputation encodes the "type" of action that should be performed by the websocket-api, so it directly correspond to a specific endpoint version. And only the endpoint is versioned (ws://bla/v1/computations) but not each internal websocket message.

**Comment by pascalseeland** [comment]
I  did finish writing the adr. Merge if you think it represents the outcome if this discussion
